# NUMPY Mini Project 1 
# (NumPy capstone — student exam analysis)
You are a data analyst. You have received raw exam scores for 8 students across 3 subjects — but the data has missing values. Work through each step.
1. Load & inspect the dataset
2. Compute per-student averages
3. Compute per-subject averages
4. Filter: who passed?
5. Summary report

### Install Libraries

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Import Libraries

In [3]:
import numpy as np

### Creation of Dataset using Numpy Array

In [4]:
stuexam = np.array([
    [85, 90, np.nan],
    [72, np.nan, 68],
    [91, 88, 95],
    [np.nan, 77, 82],
    [60, 65, 70],
    [78, 82, np.nan],
    [95, 91, 89],
    [55, np.nan, 60]
])
print(stuexam)

[[85. 90. nan]
 [72. nan 68.]
 [91. 88. 95.]
 [nan 77. 82.]
 [60. 65. 70.]
 [78. 82. nan]
 [95. 91. 89.]
 [55. nan 60.]]


### Figuring out the Rows and Columns

In [5]:
print(stuexam.shape)

(8, 3)


### Count the Missing Values

In [6]:
print(np.isnan(stuexam).sum())

5


### Search of Null value

In [7]:
for i in range(0,8):
     for j in range(0,3):
          if(np.isnan(stuexam[i][j])):
               print("NaN value found at index: ", i, j)

NaN value found at index:  0 2
NaN value found at index:  1 1
NaN value found at index:  3 0
NaN value found at index:  5 2
NaN value found at index:  7 1


### Mean Across Column

In [11]:
stu_avg=np.nanmean(stuexam, axis=1)
print(stu_avg)

[87.5        70.         91.33333333 79.5        65.         80.
 91.66666667 57.5       ]


### Replace Nan value with Mean

In [15]:
data=stuexam.copy() # Create a copy of the original array to avoid modifying it directly
print(data)
for i in range(0,8):
     for j in range(0,3):
          if(np.isnan(data[i][j])):
               data[i][j]=stu_avg[i]
print(data)


[[85. 90. nan]
 [72. nan 68.]
 [91. 88. 95.]
 [nan 77. 82.]
 [60. 65. 70.]
 [78. 82. nan]
 [95. 91. 89.]
 [55. nan 60.]]
[[85.  90.  87.5]
 [72.  70.  68. ]
 [91.  88.  95. ]
 [79.5 77.  82. ]
 [60.  65.  70. ]
 [78.  82.  80. ]
 [95.  91.  89. ]
 [55.  57.5 60. ]]


### Mean across down Row

In [ ]:
sub_avg=np.nanmean(stuexam, axis=0) # Calculation of subject-wise average, ignoring NaN values
print(sub_avg)

[76.57142857 82.16666667 77.33333333]


### Who will passed?

In [19]:
passed=stu_avg[stu_avg>=70]
print(len(passed),"Students passed the exam.")

6 Students passed the exam.


### Summary Report

In [ ]:
print("Overall Mean:",np.nanmean(stuexam))
print("Highest Score:",np.nanmax(stuexam))
print("Lowest Score:",np.nanmin(stuexam))
print("Student passed :",len(passed),"/8")
np.savetxt('results.csv', data, delimiter=',')

Overall Mean: 78.57894736842105
Highest Score: 95.0
Lowest Score: 55.0
Student passed : 6 /8
